# Generated by Django 5.0.14 on 2026-03-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('visitor_phone', models.CharField(blank=True, max_length=40)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('auto_reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_operator_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('system', 'System')], max_length=12)),
                ('source', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('system', 'System'), ('api', 'API')], max_length=12)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.supportconversation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
