# Generated by Codex on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionsubmission",
            name="file_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="contributionsubmission",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="contributions/%Y/%m/%d"),
        ),
    ]
