# Generated by Codex on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_file_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributionsubmission",
            name="file_upload",
        ),
        migrations.AlterField(
            model_name="contributionsubmission",
            name="file_path",
            field=models.CharField(max_length=500),
        ),
    ]
