# Generated by Codex on 2025-12-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_remove_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionsubmission",
            name="points_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
