# Generated by Django 5.2.4 on 2025-12-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_submission_category"),
        ("contributions", "0004_points_awarded"),
    ]

    operations = []
