# Generated by Django 5.2.4 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0005_merge_0002_submission_category_0004_points_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionsubmission",
            name="competition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WRO", "WRO"),
                    ("FLL", "FLL"),
                    ("ENJOY_AI", "Enjoy AI"),
                    ("VEX_IQ", "VEX IQ"),
                    ("VEX_V5", "VEX V5"),
                    ("OTHER", "Other competition"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contributionsubmission",
            name="preview_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
