# Generated by Django 5.2.4 on 2025-12-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_competition_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionsubmission",
            name="download_cost_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Points required to unlock and download this content.",
            ),
        ),
    ]
