# Generated by Django 5.0.14 on 2025-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0007_download_cost_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionsubmission",
            name="download_cost_points",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Points required to unlock and download this content.",
            ),
        ),
    ]
