# Generated by Django 5.0.14 on 2025-12-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_contributionsubmission_award_points"),
        ("contributions", "0009_contributionsubmission_price_vnd"),
    ]

    operations = []
