# Generated by Django 5.0.14 on 2025-12-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_submission_user_nullable"),
        ("contributions", "0010_merge_20251230_0758"),
    ]

    operations = []
