# Generated by Django 5.0.14 on 2026-01-14

from django.db import migrations, models


ROLE_GROUP_NAMES = {
    "STUDENT": "Student",
    "TEACHER": "Teacher",
    "PARENT": "Parent",
}

INTERNAL_STUDENT_GROUP_NAME = "Student nội bộ"


def forwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias

    group_by_name = {}
    for name in [*ROLE_GROUP_NAMES.values(), INTERNAL_STUDENT_GROUP_NAME]:
        group, _created = Group.objects.using(db_alias).get_or_create(name=name)
        group_by_name[name] = group

    User.objects.using(db_alias).filter(role="COMMUNITY").update(role="PARENT")

    through = User.groups.through
    role_group_ids = [group_by_name[name].id for name in ROLE_GROUP_NAMES.values()]

    through.objects.using(db_alias).filter(group_id__in=role_group_ids).delete()

    entries = []
    for user_id, role in User.objects.using(db_alias).exclude(role="").values_list("id", "role"):
        group_name = ROLE_GROUP_NAMES.get(role)
        if not group_name:
            continue
        entries.append(through(user_id=user_id, group_id=group_by_name[group_name].id))

    if entries:
        through.objects.using(db_alias).bulk_create(entries, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0002_user_social_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("PARENT", "Parent"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
