# Generated by Django 5.0.14 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="participant_campus",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="attempt",
            name="participant_dob",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="attempt",
            name="participant_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="attempt",
            name="sheets_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="sheets_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="sheets_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

