# Generated by Django 5.0.14 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0002_attempt_participants_and_sheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="blockly_state",
            field=models.TextField(
                blank=True,
                help_text="Optional: Blockly workspace JSON (from Blockly.serialization.workspaces.save) for editor-accurate preview.",
            ),
        ),
    ]

