# Generated by Django 5.0.14 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0003_question_blockly_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="scratchblocks_text",
            field=models.TextField(
                blank=True,
                help_text="Optional: Scratch blocks text (scratchblocks syntax) for Scratch-style preview.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="code_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: language name for code snippet (e.g., python).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="code_text",
            field=models.TextField(
                blank=True,
                help_text="Optional: code snippet shown under the prompt.",
            ),
        ),
    ]

