# Generated by Django 5.0.14 on 2026-01-13 00:00

from django.db import migrations, models


def infer_question_types(apps, schema_editor):
    Question = apps.get_model("blockly_quiz", "Question")
    Question.objects.exclude(scratchblocks_text="").update(question_type="scratch")
    Question.objects.filter(scratchblocks_text="").exclude(code_text="").update(
        question_type="code"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0004_question_scratchblocks_and_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blockly", "Blockly"),
                    ("scratch", "Scratch"),
                    ("code", "Code"),
                ],
                default="blockly",
                help_text="Used for filtering and random quiz generation.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                ],
                default="medium",
                help_text="Used for filtering and random quiz generation.",
                max_length=16,
            ),
        ),
        migrations.RunPython(infer_question_types, reverse_code=migrations.RunPython.noop),
    ]

