# Generated by Django 5.0.14 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0005_question_type_and_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_temporary",
            field=models.BooleanField(
                default=False,
                help_text="Temporary quizzes are generated for random practice.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="temporary_session_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Owner session key for temporary quizzes.",
                max_length=64,
            ),
        ),
    ]

