# Generated by Django 5.0.14 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("blockly_quiz", "0006_quiz_temporary_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: only members of these groups can access this quiz.",
                related_name="blockly_quizzes",
                to="auth.group",
            ),
        ),
    ]

