# Generated by Django 5.0.14 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockly_quiz", "0008_classrooms_and_assignments"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE blockly_quiz_attempt ADD COLUMN IF NOT EXISTS quiz_is_temporary_snapshot boolean NOT NULL DEFAULT false;",
                "ALTER TABLE blockly_quiz_attempt ADD COLUMN IF NOT EXISTS quiz_slug_snapshot varchar(220) NOT NULL DEFAULT '';",
                "ALTER TABLE blockly_quiz_attempt ADD COLUMN IF NOT EXISTS quiz_title_snapshot varchar(200) NOT NULL DEFAULT '';",
                "ALTER TABLE blockly_quiz_attempt ALTER COLUMN quiz_is_temporary_snapshot DROP DEFAULT;",
                "ALTER TABLE blockly_quiz_attempt ALTER COLUMN quiz_slug_snapshot DROP DEFAULT;",
                "ALTER TABLE blockly_quiz_attempt ALTER COLUMN quiz_title_snapshot DROP DEFAULT;",
            ],
            reverse_sql=[
                "ALTER TABLE blockly_quiz_attempt DROP COLUMN IF EXISTS quiz_is_temporary_snapshot;",
                "ALTER TABLE blockly_quiz_attempt DROP COLUMN IF EXISTS quiz_slug_snapshot;",
                "ALTER TABLE blockly_quiz_attempt DROP COLUMN IF EXISTS quiz_title_snapshot;",
            ],
            state_operations=[
                migrations.AddField(
                    model_name="attempt",
                    name="quiz_is_temporary_snapshot",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="attempt",
                    name="quiz_slug_snapshot",
                    field=models.CharField(blank=True, default="", max_length=220),
                ),
                migrations.AddField(
                    model_name="attempt",
                    name="quiz_title_snapshot",
                    field=models.CharField(blank=True, default="", max_length=200),
                ),
            ],
        )
    ]
