# Generated by Django 5.0.14 on 2026-02-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockly_quiz', '0009_attempt_quiz_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='quiz_is_temporary_snapshot',
            field=models.BooleanField(default=False, help_text='Snapshot of quiz temporary status at submission time.'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz_slug_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of quiz slug at submission time.', max_length=220),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz_title_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of quiz title at submission time.', max_length=200),
        ),
    ]
