# Generated by Django 5.0.14 on 2026-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblock',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('BILINGUAL_TEXT', 'Bilingual text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('GALLERY', 'Gallery'), ('QUOTE', 'Quote'), ('DIVIDER', 'Divider')], max_length=20, verbose_name='Type'),
        ),
    ]
