# Generated by Django 5.0.14 on 2026-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postblock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogApiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(default='blog.api_post_create', max_length=120)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('key_id', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog API audit log',
                'verbose_name_plural': 'Blog API audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['route', 'created_at'], name='blog_api_rt_ct_idx'), models.Index(fields=['status_code', 'created_at'], name='blog_api_sc_ct_idx'), models.Index(fields=['key_id', 'created_at'], name='blog_api_ky_ct_idx')],
            },
        ),
    ]
