# Generated by Django 5.0.14 on 2026-03-13 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_blogapiauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=80, unique=True)),
                ('source_channel', models.CharField(blank=True, max_length=40)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('command_text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('media_results', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('CREATED', 'Created'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
