# Generated by Django 5.0.14 on 2025-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gating", "0002_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unlock",
            name="method",
            field=models.CharField(
                choices=[
                    ("POINTS", "Points"),
                    ("AD", "Ad"),
                    ("SOCIAL", "Social"),
                    ("CONTRIBUTION", "Contribution"),
                    ("PAYMENT", "Payment"),
                ],
                max_length=20,
            ),
        ),
    ]
